name: Python Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Specify the Python version

    # - name: Cache Poetry virtualenv
    #   uses: actions/cache@v4
    #   with:
    #     path: ~/.cache/pypoetry/virtualenvs
    #     key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: poetry run python -m pytest # or your test command
